apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane
  annotations:
    iam.gke.io/gcp-service-account: control-plane@mindclade-development.iam.gserviceaccount.com
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifact-proxy
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-worker
automountServiceAccountToken: false
